=== doom5/doom5.batchutils/resources/xsd/configurationFile/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- XML Schema Generated from XML Document on Mon Oct 12 2020 11:36:45 
		GMT+0200 (Central European Summer Time) -->
	<!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="implementationsPackage"
					type="xs:string"></xs:element>
				<xs:element name="dbConfiguration" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="connectionType" type="xs:string"></xs:element>
							<xs:element name="driverClass" type="xs:string"></xs:element>
							<xs:element name="connectionString" type="xs:string"></xs:element>
							<xs:element name="onConnectStatement" type="xs:string"
								maxOccurs="unbounded"></xs:element>
							<xs:element name="prop" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"></xs:element>
										<xs:element name="value" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="properties"  maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="batchName" type="xs:string"></xs:element>
							<xs:element name="prop" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"></xs:element>
										<xs:element name="value" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== doom5/doom5.batchutils/resources/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xsd/configurationFile/configuration.xsd">
	<implementationsPackage>doom5.example.impl</implementationsPackage>
	<dbConfiguration>
		<connectionType>EXAMPLECONNECTION</connectionType>
		<driverClass>org.sqlite.JDBC</driverClass>
		<connectionString>jdbc:sqlite:./resources/DB.sqlite</connectionString>
		<onConnectStatement>select * from PARAMETERS</onConnectStatement>
		<prop>
			<name>nameExample</name>
			<value>valueExample</value>
		</prop>
	</dbConfiguration>
	<properties>
		<batchName>ExampleImpl</batchName>
		<prop>
			<name>name</name>
			<value>valueExampleImpl</value>
		</prop>
		<prop>
			<name>destServer</name>
			<value>server1.domain.com</value>
		</prop>
		<prop>
			<name>destShare</name>
			<value>Folder1</value>
		</prop>
		<prop>
			<name>destDomain</name>
			<value>MYDOMAIN</value>
		</prop>
		<prop>
			<name>destUser</name>
			<value>MYUSER</value>
		</prop>
		<prop>
			<name>destPass</name>
			<value>MYPASSWORD</value>
		</prop>
	</properties>
</configuration>
